### PR TITLE
Request installer

### PR DESCRIPTION
**Pull request by gildean**
This change to the installer fixes pretty much all the problems it currently has with handling proxies.

Now setting the `http_proxy`, `https_proxy`, and `no_proxy` environment variables have the desired effect (with auth etc. working as expected).

I also changed all the opening braces to be consistent and fixed all double equals and unequals to their triple counterparts.

### CODE REVIEW

**Comment by bimalkjha** [comment]
These changes fixes which issue? Do you see any bug with existing code? Thanks.

**Comment by gildean** [comment]
Yes, the current installer does not work when using a proxy but the npm registry is contacted without the proxy (i.e. setting the no_proxy env var to ignore an address).

The current installer requires the proxy settings to be set on npm, but setting those will prevent the use of a private registry that is contacted without the proxy.

This change allows the env vars to be used like they should (the local registry is contected without proxy but the post-intaller will use the proxy).

**Comment by bimalkjha** [comment]
@gildean Please let me know I should address this pull request in the same way as your other pull request or you would like to send us signed [node-ibm_db Joint Copyright cla-individual contribution](https://github.com/ibmdb/node-ibm_db/blob/master/cla_docs/node-ibm_db%20Joint%20Copyright%20cla-individual%20contribution.pdf) as documented [here](https://github.com/ibmdb/node-ibm_db/blob/master/cla_docs/Contributions.md)? Thanks.

**Comment by rmg** [comment]
In order for this to work reliably `request` will need to be bundled. Otherwise this PR will trade one installation headache for another, larger headache.

**Comment by gildean** [comment]
@rmg I don't see what you mean, there are other dependencies in this module as well, if you can't install one of them then you most likely can't install any of them. Request module in my experience installs fine on any platform. (In fact npm itself uses request as you can see [here](https://github.com/npm/npm/blob/latest/package.json#L88), so it's probably already installed on a system that does an npm install)

This pr just adds one more dependency that handles the post-install portion correctly afaik in every situation where it currently just doesn't function in the case explained above.

**Comment by rmg** [comment]
@gildean sorry for the confusion.

What I meant was that `npm` won't reliably install the listed dependencies _before_ executing this package's own `preinstall`, `install`, and `postinstall` scripts. The only way to reliably use dependencies in one of those scripts is to bundle the dependencies that are used by those scripts so that they are included in the tarball for this package.

**Comment by gildean** [comment]
@rmg You must be referencing this issue concerning npm2: https://github.com/npm/npm/issues/6926
In npm3 that bug has been fixed and the code in this pr works as intended (at least I haven't been able to reproduce the problem you and the issue describes).

**Comment by amellnik** [comment]
What's the status of this -- is there any work that needs to be done or are we just waiting for a merge?  Thanks -A

**Comment by bimalkjha** [comment]
This pull request is addressed with latest commit https://github.com/ibmdb/node-ibm_db/commit/8f95780774df243f0a6af90c68014b6c942b74f6 . Hence closing it. Thanks.

**Pull request closed without merging**
