### PR TITLE
Fix unintentional global variables

### PR DESCRIPTION
**Pull request by gildean**
This pr fixes multiple unintentional global variables.

### CODE REVIEW

**Comment by gildean** [comment]
I suggest you merge this pr asap considering the critical nature of the bugs.

**Comment by bimalkjha** [comment]
Addressed. Thanks.

**Comment by gildean** [comment]
Please merge the pr correctly, you've tried to be clever and hide the contributors from the history, but at the same time broke the fixes.
Use the code as is, it has been tested.

**Comment by bimalkjha** [comment]
@gildean What is broken and which fix is not merged from this pull request? Could you please paste that peace of code here or provide more details? Thanks.

**Pull request closed without merging**
