### PR TITLE
Adds support for named binding parameters

### PR DESCRIPTION
**Pull request by AckerApple**
Implemented using npm install of [bind-sql-string](https://www.npmjs.com/package/bind-sql-string)

The package bind-sql-string casts a query string with colon based named binding parameters into  into question marks. It also casts an object of values, that matches the named binding parameters, into an array.

Essentially, bind-sql-string casts the way we would want named binding parameters to work INTO the question mark array of values that ibm_db is compatible with.

This ALSO supports ibm_db array parameters with typing definitions. This is because an object of values, which could be a typing value, is just converted to an array the way ibm_db has always worked with.

The documentation on how bind-sql-string works can be seen here: https://www.npmjs.com/package/bind-sql-string

Thank you for your time and consideration.

Below, large example of the magic sauce converting named bindings into array of bindings:
```javascript
import queryBind from "bind-sql-string";

const sql = `
    SELECT *
    FROM   SomeTable st
    WHERE  st.SomeNumberColumn > :someNumberValue
    AND    st.SomeStringColumn = :someStringValue
    AND    st.SomeDate BETWEEN :startDate AND :endDate 
    AND    st.SomeOtherColumn<:someNumberValue
    AND    st.SomeInColumn IN (:someStringValue,'B','C')
    AND    st.SomeOtherColumn = 2+:someStringValue
    AND    st.SomeStringArg = 'keep this '':binding'''
    AND    st.SomeStringColumn IN (:multipleValues)
`;

const bindings = {
    someNumberValue:  1,
    someStringValue:  "He's got value",
    startDate: Date.now(),
    endDate: Date.now(),
    multipleValues: ["A", "B", "C"]
};

const setup = queryBind(sql, bindings);

// RESULT: {sql: string, parameters: any[]}

{
    sql: `
        SELECT *
        FROM   SomeTable st
        WHERE  st.SomeNumberColumn > ?
        AND    st.SomeStringColumn = ?
        AND    st.SomeDate BETWEEN ? AND ? 
        AND    st.SomeOtherColumn<?
        AND    st.SomeInColumn IN (?,'B','C')
        AND    st.SomeOtherColumn = 2+?
        AND    st.SomeStringArg = 'keep this '':binding'''
        AND    st.SomeStringColumn IN (?,?,?)
    `,
    parameters:[
      1, // someNumberValue
      'He\'s got value', // someStringValue
      1579032023955, // startDate
      1579032023955, // endDate
      1, // someNumberValue
      'He\'s got value', // someStringValue
      'He\'s got value', // someStringValue
      'A', 'B', 'C'
    ]
}
```

### CODE REVIEW

**Comment by AckerApple** [comment]
I only addressed one function in ibm_db called "query". Other functions will need review like querySync.

Documentation inside ibm_db is recommended.

**Comment by AckerApple** [comment]
I know we've been under tough times. This code is legit. Can we talk about it, get eyes on it?

Thank you kindly

**Comment by bimalkjha** [comment]
@AckerApple The use of colon based named binding parameters in not supported by Db2 Servers. All Db2 clients are expecting parameter markers (?) only in SQL. Changing the behavior of ibm_db different than other db2 client and drivers is not recommended.
I checked the code change in odbc.js file. Not only the style of SQL will be changed but the format of binding parameters expected by ibm_db apis too will change and it would break the existing applications of ibm_db users. We need to modify all ibm_db APIs to accept binding parameters in new format. 

If some user really want to use `bind-sql-string` package and named binding parameters in their application, they just need to add two lines of extra code for `bind-sql-string` package as below:
```javascript
const bindSqlString = require('bind-sql-string');  
const bindConfig = bindSqlString(query, params);
ibmdb.query(bindConfig.sql, bindConfig.parameters, function(err,result) { .... }
```
Infact it is just one line of extra code! 

We do not want to make `ibm_db` dependent on `bind-sql-string` package as of now. Hence, I am closing this pull request. Thanks.

**Comment by AckerApple** [comment]
Understood and thank you kindly

**Pull request closed without merging**
