### PR TITLE
Add support for i5/OS system naming

### PR DESCRIPTION
**Pull request by drudge**
We needed the ability to specify system naming while connecting to DB2 for iSeries V7R1, so I added support for passing a boolean `systemNaming` option which will enable this. The option defaults to `false` so backwards compatibility is maintained.
### Possible Values

`false` (default) – DB2 UDB CLI uses the default naming mode, which is SQL naming. Files are qualified using the period (.) delimiter. Unqualified files are resolved using either the default library or the current user ID.

`true` – DB2 UDB CLI uses the i5/OS® system naming mode. Files are qualified using the slash (/) delimiter. Unqualified files are resolved using the library list for the job.
### Usage

``` js
'use strict';

const ibmdb = require('ibm_db');

const config = 'DRIVER={DB2}...';
ibmdb.open(config, {systemNaming: true}, (err,conn) => {
  conn.query(`select count(*) from SOMEFILE`, (err, res) => {
    if (err) throw err;
    console.log(res);
  });
});
```

### CODE REVIEW

**Comment by drudge** [comment]
@bimalkjha Any change of merging this into your next release? This is related to #98.

**Comment by bimalkjha** [comment]
@drudge Please fill this form to help us: http://goo.gl/forms/EKzg7A6HZw

**Comment by drudge** [comment]
@bimalkjha Okay, I have filled out the form.

**Comment by jameswomack** [comment]
@drudge Does the connection string format stay the same?

**Comment by drudge** [comment]
@jameswomack Yes, it does.

**Comment by drudge** [comment]
@bimalkjha Any plans to merge this?

**Comment by bimalkjha** [comment]
@drudge This can be achieved by just adding "Naming=SYSTEM" in connection string. Could you please try and confirm. Connection string should be like this: `"DATABASE=AS400;HOSTNAME=HOST;UID=USER;PWD=PASS;PORT=XXX;PROTOCOL=TCPIP;NAMING=SYSTEM"`

Thanks.

**Comment by drudge** [comment]
@bimalkjha I tried that first and it did not work.

**Comment by bimalkjha** [comment]
Strange as setting attribute SQL_ATTR_DBC_SYS_NAMING or passing NAMING=SYSTEM in connection string, both sends the same instruction on server, so both should work. Could you please check again to confirm? Thanks.

**Comment by bimalkjha** [comment]
Addressed with latest commit to master. Thanks.

**Pull request closed without merging**
