### PR TITLE
Remove unnecessary locking

### PR DESCRIPTION
**Pull request by qpresley**
This PR removes more of the locking that the current changes to ibm_db master.  There are also a number of test case updates to clear up some formatting and add logging to help debug if there are errors in the nodeEE test sets.

### CODE REVIEW

**Comment by bimalkjha** [comment]
@qpresley These lockings are required for ODBC APIs to be called in sequence, else we may see unexpected behaviour. These uv_mutex are used to support asynchronous behaviour of node.js application, but inner level odbc apis are synchronous and they need to be called in sequence. f.e. SQLExecute should get called after SQLPrepare only. If we remove these locks, it might happen that one uv thread have just started execution of SQLPrepare() and at the same time other uv thread starts execution of SQLExecute(). If these lockings are creating problem, then we can look and update the code. Lockings might be at wrong place. But, if these locks are not causing any issue, then I think we should not remove it as of now. You can check below links to get more info:
https://nikhilm.github.io/uvbook/threads.html
http://grokbase.com/t/gg/nodejs/12914fegd7/uv-mutex-lock-seems-to-be-failing-in-tight-loop
Thanks and Regards,
Bimal Jha

**Comment by qpresley** [comment]
@bimaljha I don't think that the SQLPrepare and SQLExecute is a good example.  There should never be a case even in proper async programming that someone could get into a situation where they call Prepare after Execute.  If they do then their application coding is incorrect.

A better example that MAY be a reason for using uv_mutex_lock in some of these places is that each call from the Node.js code to the libuv event loop could execute in a different thread.  I don't know if this is actually the case but if it were then it would be possible for one thread to allocate a statement handle and another thread to destroy it.  This *could* get you into the situation where one is freeing the memory while the other is allocating it however I suspect that is also going to be due to poor use of async calls.

So far we have a few cases reporting inconsistent performance results or deadlocks which are all going to be due to timing of acquiring and releasing these locks.  If you aren't comfortable having all removed then a proper performance and code evaluation of each should be done to improve the consistency and results the module produces.

**Comment by bimalkjha** [comment]
@qpresley Yes, I am not comfortable with the changes because I think it may cause issues with existing applications. Our test cases are small one and not big like real apps to cover all such scenarios. The node.js application is single process application, but when the code get executed by uv thread, it is 4 threads executing ODBC APIs from the queues. When we have collected ODBC/CLI trace for a test case, in few cases have seen that SQLDriverConnect is executed by one uv thread but allocation of statement handle using same connection handle is done by another uv thread. See [clitrc.txt](https://github.com/ibmdb/node-ibm_db/files/709336/clitrc.txt) trace file collected for `test/test-binding-statement-executeSync.js` file. If we remove the locks, second thread which allocates statement handle, may start execution while driver is still waiting for connection. In current code, SQLPrepare and SQLExecute both are under same locks, so it is ensuring that it will get called in sequence.
I too feel there is scope to remove some locks by rearranging the codes, but we need time to access all locks and remove one by one. We are not confident to remove all uv locks at once from ibm_db. We'll do it in phases with testing going along. Thanks.

**Comment by bimalkjha** [comment]
@qpresley I am thinking to merge these changes. Could you please update this branch with latest of master so that I can merge it. Currently I am getting error while merging with command line too due to changes in build.zip file. Thanks.

**Comment by qpresley** [comment]
@bimaljha Have a quick look at the commits and make sure the Rebase commit contains the changes from master appropriately before merging.

**Comment by bimalkjha** [comment]
@qpresley while testing these changes, it seems the test case test-issue211.js hangs if Query 2 executed first. It happens in 3 out of 5 run. Could you please check? Thanks.

**Comment by qpresley** [comment]
@bimaljha it is a test case problem because after query 2 executes and commits it then tries to drop the table.  This ends up causing a real deadlock on the Table lock.  The drop of the table (cleanup) should be done synchronously after both query 1 and query 2 have executed and committed.  Alternatively you can leave the cleanup to the start of the test case where it already drops old lives of the table

**Pull request merged**
